// React/jwt-ddemo/src/views/Login/index.jsx
import {
  useRef
}from 'react'
import {
  useUserStore
}from '../../store/user'
import {useNavigate}from 'react-router-dom'
const Login = () =>{
  const usernameRef = useRef();
  const passwordRef = useRef();
  const {Login} = useUserStore();
  const navigate = useNavigate();
  const handleLogin = (event)=>{
    event.preventDefault();
      const username = usernameRef.current.value;
      const password = passwordRef.current.value;
      if(!username || !password){
        alert('请输入用户名和密码')
        return ;
      }

      Login({username,password});
      // setTimeout(()=>{
      //   navigate('/')
      // },1000)
  }
  return (
    <div>
      Login
      <form onSubmit={handleLogin}>
        <label htmlFor="username">username: </label>
        <input type="text" id='username' ref={usernameRef} required placeholder='请输入账号' /><br />
        <label htmlFor="password">password:  </label>
        <input type="password" id='password' ref={passwordRef} required placeholder='请输入密码' />
      <div>
           <button type='submit'>登录</button>
      </div>
      </form>
    </div>
  )
}

export default Login;

// vue/vue-login/src/view/Login.vue
<template>
  <div>
    <h1>Login</h1>
    <form @submit.prevent="handleLogin">
      <input type="text" placeholder="用户名" required v-model="username">
      <input type="password" placeholder="密码" required v-model="password">
      <button type="submit"> 登录 </button>
    </form>
  </div>
</template>

<script lang="ts" setup>
// @ts-nocheck

import { ref } from 'vue'
import { useRouter } from 'vue-router'

import { useUserStore } from "@/stores/user";

import { login } from "@/api/login";

const username = ref("");
const password = ref("");
const userStore = useUserStore();
const router = useRouter()

const handleLogin = async () => {
  try {
    const data = await login({
      username: username.value,
      password: password.value
    })
    userStore.setToken(data.token);
    userStore.setUsername(data.username);

    router.push("/");
  } catch (error) {
    console.log(error);
  }
}

</script>

<style scoped></style>
