// vue/vue-login/src/view/Login.vue
<template>
  <div>
    <h1>Login</h1>
    <form @submit.prevent="handleLogin">
      <input type="text" placeholder="用户名" required v-model="username">
      <input type="password" placeholder="密码" required v-model="password">
      <button type="submit"> 登录 </button>
    </form>
  </div>
</template>

<script lang="ts" setup>
// @ts-nocheck

import { ref } from 'vue'
import { useRouter } from 'vue-router'

import { useUserStore } from "@/stores/user";

import { login } from "@/api/login";

const username = ref("");
const password = ref("");
const userStore = useUserStore();
const router = useRouter()

const handleLogin = async () => {
  try {
    const data = await login({
      username: username.value,
      password: password.value
    })
    userStore.setToken(data.token);
    userStore.setUsername(data.username);

    router.push("/");
  } catch (error) {
    console.log(error);
  }
}

</script>

<style scoped></style>

// React/deep-router/src/pages/Login/index.jsx
import {
  useState
}from 'react'
import {
  useNavigate,
  useLocation
}from 'react-router-dom'
const Login = ()=>{
  
  const [username,setUsername] = useState('');
  const [password,setPassword] = useState('');
  
  const localtion = useLocation();
  //console.log(localtion.state.from);
  const navigate = useNavigate();//获得跳转的能力

  const handleSubmint = (e)=>{
    e.preventDefault();
    if(username==='admin'&&password==='123'){
      localStorage.setItem('isLogin',"true");
      navigate( '/pay');
    }else{
      alert('失败')
    }
  }
  return (
    <div>
      Login
      <form onSubmit={handleSubmint}>
         <h1>登陆页面</h1>
         <input type="text"
          placeholder="请输入账号" 
           required 
           value={username}
           onChange={(e)=>{setUsername(e.target.value)}}
           />
           <br />
         <input 
         type="password"
          placeholder="请输入密码" 
          value={password}
           required 
          onChange={(e)=>{setPassword(e.target.value)}}
          />
          <br />
          <button type='submit'>登陆</button>
      </form>
    </div>
  )
}

export default Login
